name: Python DevSecOps Pipeline (GitHub Actions)

on: 
    push:
        branches: 
            - master
    pull_request:
        branches:
            - master

permissions:
    # Global permissions (used if job permissions are not set)
    contents: read
    security-events: write
    actions: read

env:
    IMAGE_NAME: pygoat
    REGISTRY: ghcr.io
    IMAGE_TAG: ${{ github.sha }}

jobs:
    security_scan:
        runs-on: ubuntu-latest
        # FIX 1: Explicitly defining permissions at the job level is REQUIRED for SARIF uploads to work reliably.
        permissions:
            contents: read
            security-events: write
        steps:
            - name: Checkout Code 
              uses: actions/checkout@v4
              with: 
                fetch-depth: 0 # Keep 0 to ensure Gitleaks scans the full history

            - name: Set up Python
              uses: actions/setup-python@v5 
              with: 
                python-version: '3.11' 

            - name: Install Tools (Bandit, Semgrep)
              run: |
                pip install bandit semgrep 
                
            - name: Install Code Quality Tools
              run: pip install black flake8

            - name: Run Flake8 Linter
              run: flake8 .
              continue-on-error: true 

            - name: Run Black Formatter Check
              run: black . --check
              continue-on-error: true 

            - name: Install Project Dependencies
              run: pip install -r requirements.txt

            - name: Static Application Security Testing (SAST) with Bandit (JSON)
              run: |
                bandit -r . -o bandit-report.json -f json || true
              continue-on-error: true
            
            - name: SAST with Semgrep (SARIF Output)
              uses: returntocorp/semgrep-action@v1
              with:
                config: "auto"
                # FIX 3: Explicitly define output file name for reliability
                output: semgrep-report.sarif 
              continue-on-error: true
            
            - name: SCA (Dependency Check) with OWASP Dependency-Check Action (SARIF)
              uses: dependency-check/Dependency-Check_Action@main
              id: dependency_check_action
              with:
                project: 'Python-App'
                path: '.'
                format: 'SARIF'
                out: dependency-check-reports
              continue-on-error: true
            
            - name: Secrets Detection with GitLeaks (SARIF)
              uses: zricethezav/gitleaks-action@v1
              with: 
                args: --report-path=gitleaks-report.sarif --format=sarif
              continue-on-error: true 
            
            - name: Upload SAST/SCA/Secrets SARIF Reports to GitHub
              id: sarif_prep
              run: |
                sarif_files=""
                
                # Check for files and build list (now using the explicitly defined names)
                if [ -f semgrep-report.sarif ]; then sarif_files+=" semgrep-report.sarif"; fi
                if [ -f dependency-check-reports/dependency-check-report.sarif ]; then sarif_files+=" dependency-check-reports/dependency-check-report.sarif"; fi
                if [ -f gitleaks-report.sarif ]; then sarif_files+=" gitleaks-report.sarif"; fi
                
                # Output the list to be used by the upload-sarif action
                echo "sarif_list=$sarif_files" >> $GITHUB_OUTPUT 
                echo "Found SARIF files: $sarif_files"

            - name: Perform SARIF Upload
              uses: github/codeql-action/upload-sarif@v3 
              if: always() && steps.sarif_prep.outputs.sarif_list != ''
              with: 
                sarif_file: ${{ steps.sarif_prep.outputs.sarif_list }}
              continue-on-error: true

            - name: Publish Pre-Build Artifacts for Container Job
              # FIX 4: Explicitly publish reports so the next job can download them.
              uses: actions/upload-artifact@v4
              with:
                  name: pre-build-reports
                  path: |
                      *.json
                      dependency-check-reports/

    container_scan: 
        runs-on: ubuntu-latest 
        needs: security_scan
        # FIX 1: Explicitly defining permissions at the job level.
        permissions:
            packages: write
            contents: write # Need write permissions to download artifacts
            security-events: write # Need security-events permission for SARIF uploads
        steps:
            - name: Download Pre-Build Reports
              # FIX 4: Download artifacts from the previous job
              uses: actions/download-artifact@v4
              with:
                  name: pre-build-reports
                  path: . # Download to current workspace for later artifact upload
            
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Checkout Code 
              uses: actions/checkout@v4 

            - name: Docker Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5 
              with: 
                context: .
                push: true
                tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                # Attestation flags remain disabled due to runner limitations

            # Trivy is now used for both Filesystem/SBOM and Image Scanning (replacing Syft/Grype)
            - name: SBOM Generation and Vulnerability Scan (Trivy Filesystem)
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                format: 'sarif'
                output: 'trivy-fs-report.sarif'
                exit-code: '0' 
              continue-on-error: true

            - name: Upload Trivy Filesystem Scan SARIF report
              uses: github/codeql-action/upload-sarif@v3
              if: always() && hashFiles('trivy-fs-report.sarif') != ''
              with:
                sarif_file: trivy-fs-report.sarif

            - name: Docker Scout Scan 
              uses: docker/scout-action@v1 
              with: 
                command: cves 
                image: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                only-severity: high,critical

            - name: Image Scan with Trivy (SARIF)
              uses: aquasecurity/trivy-action@master
              with: 
                image-ref: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                format: sarif
                output: trivy-image-report.sarif
                exit-code: '0'
              continue-on-error: true 

            - name: Upload Trivy Image Scan SARIF report
              uses: github/codeql-action/upload-sarif@v3
              if: always() && hashFiles('trivy-image-report.sarif') != ''
              with:
                sarif_file: trivy-image-report.sarif
            
            - name: Upload Security Artifacts (Mixed JSON/SPDX/HTML)
              # This step now uploads all new reports AND the reports downloaded from the previous job.
              uses: actions/upload-artifact@v4 
              if: always()
              with:
                name: security-reports 
                path: |
                    *.json
                    *.spdx.json
                    *.html
                    dependency-check-reports/*.sarif
                    *.sarif