name: Python DevSecOps Pipeline (GitHub Actions)

on: 
    push:
        branches: 
            - master
    pull_request:
        branches:
            - master

permissions:
    contents: read
    security-events: write
    actions: read

env:
    IMAGE_NAME: pygoat
    REGISTRY: ghcr.io
    IMAGE_TAG: ${{ github.sha }}

jobs:
    security_scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code 
              uses: actions/checkout@v4
              with: 
                fetch_depth: 0

            - name: Set up Python
              uses: actions/setup-python@v5 
              with: 
                # Using 3.11 as a stable middle ground for dependencies
                python-version: '3.11' 

            - name: Install Tools (Bandit, Semgrep)
              run: |
                pip install bandit semgrep 
                
            - name: Install Code Quality Tools
              run: pip install black flake8

            - name: Run Flake8 Linter
              run: flake8 .
              continue-on-error: true 

            - name: Run Black Formatter Check
              run: black . --check
              continue-on-error: true 

            - name: Install Project Dependencies
              run: pip install -r requirements.txt

            - name: Static Application Security Testing (SAST) with Bandit (JSON)
              run: |
                # Bandit outputs JSON (not SARIF natively)
                bandit -r . -o bandit-report.json -f json || true
              continue-on-error: true
            
            - name: SAST with Semgrep (SARIF Output)
              # Semgrep is set to output SARIF
              uses: returntocorp/semgrep-action@v1
              with:
                config: "auto"
                output: semgrep-report.sarif
              continue-on-error: true
            
            - name: SCA (Dependency Check) with OWASP Dependency-Check Action (SARIF)
              # Using the dedicated GitHub Action for caching/speed
              uses: dependency-check/Dependency-Check_Action@main
              id: dependency_check_action
              with:
                project: 'Python-App'
                path: '.'
                format: 'SARIF'
                out: dependency-check-reports # Outputting to a directory
              continue-on-error: true
            
            - name: Secrets Detection with GitLeaks (SARIF)
              uses: zricethezav/gitleaks-action@v1
              with: 
                args: --report-path=gitleaks-report.sarif --format=sarif
              continue-on-error: true 
            
            - name: Upload SAST/SCA/Secrets SARIF Reports to GitHub
              # FIX: Use a shell script to create an environment variable containing only existing files.
              # This prevents the job from failing when a tool finds no issues and doesn't create a file.
              id: sarif_prep
              run: |
                sarif_files=""
                # Check and add files only if they exist
                if [ -f semgrep-report.sarif ]; then sarif_files+=" semgrep-report.sarif"; fi
                if [ -f dependency-check-reports/dependency-check-report.sarif ]; then sarif_files+=" dependency-check-reports/dependency-check-report.sarif"; fi
                if [ -f gitleaks-report.sarif ]; then sarif_files+=" gitleaks-report.sarif"; fi
                
                # Output the list to be used by the upload-sarif action
                echo "sarif_list=$sarif_files" >> $GITHUB_OUTPUT

            - name: Perform SARIF Upload
              uses: github/codeql-action/upload-sarif@v3 
              if: always() && steps.sarif_prep.outputs.sarif_list != ''
              with: 
                sarif_file: ${{ steps.sarif_prep.outputs.sarif_list }}
              continue-on-error: true

    container_scan: 
        runs-on: ubuntu-latest 
        needs: security_scan
        steps:
            - name: Checkout Code 
              uses: actions/checkout@v4 

            - name: Docker Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Docker Image
              uses: docker/build-push-action@v5 
              with: 
                context: .
                push: true
                tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                # FIX 1: Disabled unsupported attestation flags
                # provenance: true 
                # sbom: true 
            
            # Trivy now covers SBOM generation and vulnerability scanning for the filesystem
            - name: SBOM Generation and Vulnerability Scan (Trivy Filesystem)
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                format: 'sarif'
                output: 'trivy-fs-report.sarif'
                exit-code: '0' # Don't fail the job if issues are found
              continue-on-error: true

            - name: Upload Trivy Filesystem Scan SARIF report
              # FIX 2/3 Resilience: Only attempt upload if the file exists (by checking previous step status).
              uses: github/codeql-action/upload-sarif@v3
              if: always() && hashFiles('trivy-fs-report.sarif') != ''
              with:
                sarif_file: trivy-fs-report.sarif

            - name: Docker Scout Scan 
              uses: docker/scout-action@v1 
              with: 
                command: cves 
                image: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                only-severity: high,critical

            - name: Image Scan with Trivy (SARIF)
              uses: aquasecurity/trivy-action@master
              with: 
                image-ref: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                format: sarif
                output: trivy-image-report.sarif
                exit-code: '0' # Don't fail the job if issues are found
              continue-on-error: true 

            - name: Upload Trivy Image Scan SARIF report
              # FIX 2/3 Resilience: Only attempt upload if the file exists.
              uses: github/codeql-action/upload-sarif@v3
              if: always() && hashFiles('trivy-image-report.sarif') != ''
              with:
                sarif_file: trivy-image-report.sarif
            
            - name: Upload Security Artifacts (Mixed JSON/SPDX/HTML)
              uses: actions/upload-artifact@v4 
              if: always()
              with:
                name: security-reports 
                path: |
                    *.json
                    *.spdx.json
                    *.html
                    dependency-check-reports/*.sarif